{% set name = "sagemaker-core" %}
{% set version = "1.0.71" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sagemaker_core-{{ version }}.tar.gz
  sha256: a69c20b6edb379dd08272692822905d2ee2ac423ba50c386c0ef604c5b6d1a56

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - boto3 >=1.35.36,<2.0.0
    - pydantic >=2.0.0,<3.0.0
    - pyyaml >=6.0,<7.0
    - jsonschema <5.0.0
    - platformdirs >=4.0.0,<5.0.0
    - rich >=13.0.0,<15.0.0
    - mock >4.0,<5.0
    - importlib-metadata <=9.0,>=1.4.0

test:
  imports:
    - sagemaker_core
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aws/sagemaker-core/
  summary: An python package for sagemaker core functionalities
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  dev_url: https://github.com/aws/sagemaker-python-sdk/
  doc_url: https://sagemaker-core.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - claytonparnell
    - benieric
    - mufaddal-rohawala
